### ISSUE TITLE
Which gramps database format?

### ISSUE THREAD

**Issue by uxcq** [FunThomas424242/files2gramps#1]
This is for the Genealogy project [Gramps XML](https://github.com/gramps-project/gramps) database format right?   What [version does it support](https://gramps-project.org/wiki/index.php?title=Gramps_XML)?

You may want to add a link?

Other similarly named projects:
 *  [GRAMPS: A Programming Model for Graphics Pipelines](http://graphics.stanford.edu/papers/gramps-tog/)
 * Or the Chess program [Gramps](https://books.google.com.au/books?id=iwjS--W2mG8C&pg=PA263&lpg=PA263&dq=gramps+software+-genealogy+-family&source=bl&ots=I0lfgSrYmQ&sig=AGEi8uuQtYKQXBrmq9AlljY_NgU&hl=en&sa=X&ved=0ahUKEwiXrdHpjcrQAhUEjpQKHWW6AQI4FBDoAQgZMAA#v=onepage&q=gramps%20software%20-genealogy%20-family&f=false)

**Comment by FunThomas424242** [comment]
Oh hello, 
yes i wrote/write the lib to support an export into the gramps database format gpkg. But i am currently not familar with the gramps program and format, so i does not know the version currently. The header of analysed files say 4.1.1:

> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE database PUBLIC "-//Gramps//DTD Gramps XML 1.6.0//EN"
> "http://gramps-project.org/xml/1.6.0/grampsxml.dtd">
> <database xmlns="http://gramps-project.org/xml/1.6.0/">
>   <header>
>     <created date="2016-11-19" version="4.1.1"/>
>     <researcher>
>     </researcher>
>   </header>
> 

**But my lib does not generate the data.xml !** I need this lib for a editor which should export to gramps. 
The editor [ahnen.dsl](https://github.com/FunThomas424242/ahnen.dsl) is under development. He should generate the data.xml in the future. 

I have currently only analysed the zip mechanik. So i have implement:
data.xml ->gzip -> data.gramps + media folder -> tar -> gzip = gpkg.
(a very simple project to learn, but in the future maybe usefull)

Why have i wrote the lib before the editor is finished? There is a interesting technical problem. The editor is based on xtext and eclipse osgi technology. I would learn to include a dependency of a native not eclipse osgi bundle. This is my motivation currently.

**Comment by uxcq** [comment]
Thank you for the explanation.  Enjoy learning 👍

**Comment by FunThomas424242** [comment]
Thanks for the hint, its very nice.
You are a gramps developer or you developed an program to support gramps?

By the way, currently i move my package at bintray to another repository at bintray. The request is currently pending.

**Comment by uxcq** [comment]
Neither, just interested in Genealogy and I use Gramps.

Thanks 👍
